global:
  smtp_smarthost: 'smtp.mxhichina.com:465'
  smtp_from: '123@qq.com'
  smtp_auth_username: '123@qq.com'
  smtp_auth_password: '****'
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10m
  receiver: live-monitoring

receivers:
- name: 'live-monitoring'
  email_configs:
  - to: 'mengqingfang@highershine.com'
