version: "3"
services: 
  redis:
    image: redis
    ports:
    - "6379:6379"
  pg-redis:
    image: dalongrong/pgspider:redis
    ports:
    - "5432:5432"
    environment: 
    - "POSTGRES_PASSWORD:dalong"
