{
 "title": "ClickHouse Performance Monitor",
 "description": "ClickHouse Performance Monitor",
 "tags": [
  "clickhouse",
  "performance"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    CurrentMetric_MemoryTracking MemoryUsed\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 4) * 4) * 1000 as t,\n    CurrentMetric_MemoryTracking MemoryUsed\nFROM system.metric_log\n\nWHERE event_date >= toDate(1608181966) AND event_time >= toDateTime(1608181966)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_Query\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 2) * 2) * 1000 as t,\n    ProfileEvent_Query\nFROM system.metric_log\n\nWHERE event_date >= toDate(1608167900) AND event_time >= toDateTime(1608167900)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "Failed QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_FailedQuery\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 2) * 2) * 1000 as t,\n    ProfileEvent_OSIOWaitMicroseconds\nFROM system.metric_log\nWHERE event_date >= toDate(1608170448) AND event_time >= toDateTime(1608170448)\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "Write Rows Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "row/s" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_InsertedRows\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 2) * 2) * 1000 as t,\n    ProfileEvent_InsertedRows\nFROM system.metric_log\n\nWHERE event_date >= toDate(1608170541) AND event_time >= toDateTime(1608170541)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "Write Bytes Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_InsertedBytes\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 2) * 2) * 1000 as t,\n    ProfileEvent_InsertedBytes\nFROM system.metric_log\n\nWHERE event_date >= toDate(1608170556) AND event_time >= toDateTime(1608170556)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "Merged Rows Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "rows/s" }
   ],
   "targets": [
    {
     "database": "system",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_MergedRows\nFROM $table\n\nWHERE $timeFilter\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 2) * 2) * 1000 as t,\n    ProfileEvent_MergedRows\nFROM system.metric_log\n\nWHERE event_time >= toDateTime(1608025436)",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "Merged Uncompressed Bytes Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "database": "system",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_MergedUncompressedBytes\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 2) * 2) * 1000 as t,\n    ProfileEvent_MergedUncompressedBytes\nFROM system.metric_log\n\nWHERE event_time >= toDateTime(1608170461)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "HTTP Connection",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    CurrentMetric_HTTPConnection\nFROM $table\n\nWHERE $timeFilter\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 2) * 2) * 1000 as t,\n    CurrentMetric_TCPConnection\nFROM system.metric_log\n\nWHERE event_date >= toDate(1608021670) AND event_time >= toDateTime(1608021670)",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "TCP Connection",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    CurrentMetric_TCPConnection\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 2) * 2) * 1000 as t,\n    CurrentMetric_TCPConnection\nFROM system.metric_log\n\nWHERE event_date >= toDate(1608170586) AND event_time >= toDateTime(1608170586)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "CPU Wait Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_OSCPUWaitMicroseconds\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 2) * 2) * 1000 as t,\n    ProfileEvent_OSCPUWaitMicroseconds\nFROM system.metric_log\n\nWHERE event_date >= toDate(1608170595) AND event_time >= toDateTime(1608170595)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "IO Wait Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_OSIOWaitMicroseconds\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 2) * 2) * 1000 as t,\n    ProfileEvent_OSIOWaitMicroseconds\nFROM system.metric_log\n\nWHERE event_date >= toDate(1608170605) AND event_time >= toDateTime(1608170605)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "Zookeeper Wait Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 48 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_ZooKeeperWaitMicroseconds\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 2) * 2) * 1000 as t,\n    ProfileEvent_ZooKeeperWaitMicroseconds\nFROM system.metric_log\n\nWHERE event_date >= toDate(1608171963) AND event_time >= toDateTime(1608171963)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "database": "system",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    name as Name,\n    path as Path,\n    free_space as Free,\n    total_space as Total,\n    1 - free_space/total_space as Used\nFROM $table",
     "rawQuery": "SELECT\n    name as Name,\n    path as Path,\n    free_space as Free,\n    total_space as Total,\n    1 - free_space/total_space as Used\nFROM system.disks",
     "round": "0s",
     "table": "disks"
    }
   ]
  },
  {
   "title": "Table Info Basic",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "database": "system",
     "dateTimeColDataType": "metadata_modification_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    database as DatabaseName,\n    name as TableName,\n    total_rows as TotalRows,\n    total_bytes as TotalBytes\nFROM $table\n\nWHERE database != 'system'\n",
     "rawQuery": "SELECT\n    database as DatabaseName,\n    name as TableName,\n    total_rows as TotalRows,\n    total_bytes as TotalBytes\nFROM system.tables\n\nWHERE database != 'system'",
     "round": "0s",
     "table": "tables"
    },
    {
     "database": "system",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    database as DatabaseName,\n    table as TableName,\n    count(1) as ColumnCnt\nFROM $table\n\nWHERE database != 'system'\n\nGROUP BY DatabaseName, TableName",
     "rawQuery": "SELECT\n    database as DatabaseName,\n    table as TableName,\n    count(1) as ColumnCnt\nFROM system.columns\n\nWHERE database != 'system'\n\nGROUP BY DatabaseName, TableName",
     "round": "0s",
     "table": "columns"
    }
   ]
  }
 ]
}